icons = "awesome"

[theme]
name = "gruvbox-dark"
[theme.overrides]
idle_bg = "#000000"
idle_fg = "#39DDDD"
info_bg = "#21C2C2"
info_fg = "#000000"
good_bg = "#21C2C2"
good_fg = "#000000"
warning_bg = "#DDDD39"
warning_fg = "#000000"
critical_bg = "#DD39DD"
critical_fg = "#000000"
separator = ""
[[block]]
block = "backlight"

[[block]]
block = "battery"
device = "BAT0"
format = "0: {percentage}%"

[[block]]
block = "battery"
device = "BAT1"
format = "1: {percentage}%"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 60

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "net"
device = "wlp4s0"
ssid = true
signal_strength = true
interval = 5
speed_up = false
hide_inactive = true
hide_missing = true

[[block]]
block = "temperature"
collapsed = true

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%F %R"
timezone = "Europe/Vilnius"

